# Question 1

In [1]:
import numpy as np
f=np.array([1,2,3,4,5])
f=f.astype(int)
def vander_matrix(a):
    d=np.vander(a,N=None, increasing=False)
    return d
vander_matrix(f)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [7]:
#Implementation of vander():

import numpy as np
empty=np.ones(25).reshape(5,5)
empty=empty.astype(int)

f1=np.array([1,2,3,4,5])
f1=f1.astype(int)
N=len(f1)
for i in range(len(f1)):
    for j in range(len(f1)):
        empty[i][j]=f1[i]**(N-j-1)
empty

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

# Question 2

In [4]:
import numpy as np
arr=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
arr

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [5]:
def moving_average(a):
    
    window=3
    res=0
    arr1=np.array([])
    for i in range(len(a)-window+1):
        res=0
        for j in range(i,window+i):
            res=a[j]+res
        arr1=np.append(arr1,res/window)
    arr1=arr1.astype(int)   
    return arr1

In [6]:
moving_average(arr)

array([  5,   4,   5,   6,   9,  28,  49,  72,  84,  93, 116])